<a href="https://colab.research.google.com/github/karsakami/Math-for-Machine-Deep-Learning/blob/main/Matrix_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Matrix** - another kind of tensor, they are two dimensional array of numbers
First number, if we say that shape of our matrix is (3, 2), is rows and second is columns

In [ ]:
import numpy as np

x = np.array([[25,2], [5,26], [3,7]])
x

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [ ]:
#first value is rows and second columns
x.shape

(3, 2)

In [ ]:
# total number of elements
x.size

6

In [ ]:
# select third row
x[2,:]

array([3, 7])

In [ ]:
# select first column
x[:,0]

array([25,  5,  3])

# Matrices in PyTorch

In [ ]:
import torch

x_pt = torch.tensor([[25,2], [5,26], [3,7]])
x_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [ ]:
x_pt.shape

torch.Size([3, 2])

In [ ]:
# second row
x_pt[1,:]

tensor([ 5, 26])

#Matrices in TensorFlow

In [ ]:
import tensorflow as tf

x_tf = tf.Variable([[25,2], [5,3], [6,7]])
x_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5,  3],
       [ 6,  7]], dtype=int32)>

In [ ]:
tf.rank(x_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
tf.shape(x_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [ ]:
x_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 3], dtype=int32)>